#!/usr/bin/env zsh

# Set colors
cCyan="\033[0;36m"
cCyanBold="\033[1;36m"
cRed="\033[0;31m"
cBlue="\033[0;34m"
cNone="\033[0m"

# Define name
ttlPlain=swiftpaper
ttl=$cCyanBold$ttlPlain$cNone

# Set filenames for before and after commands
runBefore="$HOME/.swiftpaper_before"
runAfter="$HOME/.swiftpaper_after"

# Check for init; show help otherwise
initCommand=init
[[ $1 = $initCommand ]] || {

	# Show help
	echo -e "$ttl sets you up a simple Swift environment."
	echo -e "To start, navigate into your target directory and run $cCyan$ttlPlain $initCommand$cNone."

	# Exit
	exit 0
}

# List files and directories that will stop the script if they already exist in the present directory
toxicFiles=".gitignore
main.swift"
toxicDirs="src
.vscode"

# Check for toxic files and directories
echo $toxicFiles | while read -r tF
do
	[[ -f "./$tF" ]] && {

		# Explain
		>&2 echo -e "The following file already exists in this directory:"
		>&2 echo -e "  $cRed$tF$cNone"
		>&2 echo -e "Please run $ttl in a clean directory."

		# Exit
		exit 1
	}
done
echo $toxicDirs | while read -r tD
do
	[[ -d "./$tD" ]] && {

		# Explain
		>&2 echo -e "The following directory already exists in this directory:"
		>&2 echo -e "    $cBlue$tD$cNone"
		>&2 echo -e "Please run $ttl in a clean directory."

		# Exit
		exit 1
	}
done

# Set filenames for before and after commands
runBefore="$HOME/.swiftpaper_before"
runAfter="$HOME/.swiftpaper_after"

# Source before command
[ -f $runBefore ] && source $runBefore

# Set source directory
dC=${0:a:h}/toCopy

# Copy files
cp $dC/gitignore ./.gitignore
cp $dC/main.swift ./main.swift

# Copy directories
cp -r $dC/src ./src
cp -r $dC/vscode ./.vscode

# Source after command
[ -f $runAfter ] && source $runAfter

# Show done message and refer to VSCode extensions
# ROAD WORK #TEMP

# Exit
exit 0
