#!/usr/bin/env zsh

# Set colors
cCyan="\033[0;36m"
cCyanBold="\033[1;36m"
cRed="\033[0;31m"
cBlue="\033[0;34m"
cNone="\033[0m"

# Define name
ttlPlain=swiftpaper
ttl=$cCyanBold$ttl$cNone

# Check for init; show help otherwise
initCommand=init
[[ $1 = init ]] || {

	# Show help
	echo -e "$cCyanBold""swiftpaper$cNone sets you up a simple Swift environment."
	echo -e "To start, navigate into your target directory and run $cCyan$ttlPlain $initCommand$cNone."

	# Exit
	exit 0
}

# List files and directories that will stop the script if they already exist in the present directory
toxicFiles=".gitignore
main.swift"
toxicDirs="src
.vscode"

# Check for toxic files and directories
echo $toxicFiles | while read -r tF
do
	[[ -f "./$tF" ]] && {

		# Explain
		echo -e "The following file already exists in this directory:"
		echo -e "    $cRed$tF$cNone"
		echo -e "Please run $ttl in a clean directory."

		# Exit
		exit 1
	}
done
echo $toxicDirs | while read -r tD
do
	[[ -d "./$tD" ]] && {

		# Explain
		echo -e "The following directory already exists in this directory:"
		echo -e "    $cBlue$tD$cNone"
		echo -e "Please run $ttl in a clean directory."

		# Exit
		exit 1
	}
done
